// WARNING: This file has automatically been generated on Sat, 21 Jul 2018 13:50:37 EDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package wgh

const (
	// GenlName as defined in wgh/wireguard.h:125
	GenlName = "wireguard"
	// GenlVersion as defined in wgh/wireguard.h:126
	GenlVersion = 1
	// KeyLen as defined in wgh/wireguard.h:128
	KeyLen = 32
	// CmdMax as defined in wgh/wireguard.h:135
	CmdMax = (__CmdMax - 1)
	// DeviceAMax as defined in wgh/wireguard.h:152
	DeviceAMax = (_DeviceALast - 1)
	// PeerAMax as defined in wgh/wireguard.h:171
	PeerAMax = (_PeerALast - 1)
	// AllowedipAMax as defined in wgh/wireguard.h:180
	AllowedipAMax = (_AllowedipALast - 1)
)

// wgCmd as declared in wgh/wireguard.h:130
type wgCmd int32

// wgCmd enumeration from wgh/wireguard.h:130
const (
	CmdGetDevice = iota
	CmdSetDevice = 1
	__CmdMax     = 2
)

// wgdeviceFlag as declared in wgh/wireguard.h:137
type wgdeviceFlag int32

// wgdeviceFlag enumeration from wgh/wireguard.h:137
const (
	DeviceFReplacePeers = uint32(1) << 0
)

// wgdeviceAttribute as declared in wgh/wireguard.h:140
type wgdeviceAttribute int32

// wgdeviceAttribute enumeration from wgh/wireguard.h:140
const (
	DeviceAUnspec     = iota
	DeviceAIfindex    = 1
	DeviceAIfname     = 2
	DeviceAPrivateKey = 3
	DeviceAPublicKey  = 4
	DeviceAFlags      = 5
	DeviceAListenPort = 6
	DeviceAFwmark     = 7
	DeviceAPeers      = 8
	_DeviceALast      = 9
)

// wgpeerFlag as declared in wgh/wireguard.h:154
type wgpeerFlag int32

// wgpeerFlag enumeration from wgh/wireguard.h:154
const (
	PeerFRemoveMe          = uint32(1) << 0
	PeerFReplaceAllowedips = uint32(1) << 1
)

// wgpeerAttribute as declared in wgh/wireguard.h:158
type wgpeerAttribute int32

// wgpeerAttribute enumeration from wgh/wireguard.h:158
const (
	PeerAUnspec                      = iota
	PeerAPublicKey                   = 1
	PeerAPresharedKey                = 2
	PeerAFlags                       = 3
	PeerAEndpoint                    = 4
	PeerAPersistentKeepaliveInterval = 5
	PeerALastHandshakeTime           = 6
	PeerARxBytes                     = 7
	PeerATxBytes                     = 8
	PeerAAllowedips                  = 9
	_PeerALast                       = 10
)

// wgallowedipAttribute as declared in wgh/wireguard.h:173
type wgallowedipAttribute int32

// wgallowedipAttribute enumeration from wgh/wireguard.h:173
const (
	AllowedipAUnspec   = iota
	AllowedipAFamily   = 1
	AllowedipAIpaddr   = 2
	AllowedipACidrMask = 3
	_AllowedipALast    = 4
)
