name: Static Analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.19]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@HEAD

    - name: Print staticcheck version
      run: staticcheck -version

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run go vet
      run: go vet ./...
